### ISSUE TITLE
Webpack5 (Angular12)

### ISSUE THREAD

**Issue by cwistedt** [tonto7973/jasmine-test-cases#15]
Created a new project using angular cli:
> Angular CLI: 12.0.2
> Node: 12.17.0
> Package Manager: npm 6.14.4
> OS: win32 x64
> 
> Angular:
> 
> Package                      Version
> ------------------------------------------------------
> @angular-devkit/architect    0.1200.2 (cli-only)
> @angular-devkit/core         12.0.2 (cli-only)
> @angular-devkit/schematics   12.0.2 (cli-only)
> @schematics/angular          12.0.2 (cli-only)
> 

Ran the tests and they worked:
> ng test

Installed jasmine-test-cases as a dev dependency:
> npm i jasmine-test-cases --save-dev

Ran the tests:
> ng test

Got this output:
> Chrome 91.0.4472.77 (Windows 10) ERROR
>   An error was thrown in afterAll
>   Uncaught ReferenceError: process is not defined
>   ReferenceError: process is not defined
>       at Object.663 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/chalk/index.js:8:1)
>       at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
>       at http://localhost:9876/_karma_webpack_/webpack:/node_modules/jasmine-test-cases/lib/core/colorify.js:5:36
>       at Object.666 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jasmine-test-cases/lib/core/colorify.js:7:2)
>       at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
>       at Object.802 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jasmine-test-cases/lib/core/parametrify.js:5:18)
>       at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
>       at Object.424 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jasmine-test-cases/lib/core/wrap.js:3:21)
>       at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
> Chrome 91.0.4472.77 (Windows 10): Executed 0 of 0 ERROR (0.012 secs / 0 secs)
> Chrome 91.0.4472.77 (Windows 10) ERROR
>   Disconnected Client disconnected from CONNECTED state (transport close)
> Chrome 91.0.4472.77 (Windows 10): Executed 0 of 0 ERROR (0.012 secs / 0 secs)
> Chrome 91.0.4472.77 (Windows 10) ERROR
>   Disconnected Client disconnected from CONNECTED state (transport close)

Angular12 uses Webpack5 that has some changes in how the environment variable is handled:
> https://stackoverflow.com/questions/41359504/webpack-bundle-js-uncaught-referenceerror-process-is-not-defined

**Comment by cwistedt** [comment]
Sorry. This seems to be an chalk issue.

**Comment by cwistedt** [comment]
Ill leave this here if anyone wants to know how i solved it:

Installed these devDependencies:
> "@angular-builders/custom-webpack": "^12.0.0",
> "process": "0.11.10",

This is my angular.conf for testing:
```
        "test": {
          "builder": "@angular-builders/custom-webpack:karma",
          "options": {
            "customWebpackConfig": {
              "path": "./extra-webpack.config.js"
            },
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          }
        }
```

This is my extra-webpack.conf.js:
```
var webpack = require('webpack');
module.exports = {
  plugins: [
      new webpack.ProvidePlugin({
             process: 'process/browser',
      }),
  ],
}

```

Rerefences:
https://stackoverflow.com/questions/65018431/webpack-5-uncaught-referenceerror-process-is-not-defined
